### ISSUE TITLE
Movement of all creatures have some bugs.

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#512]
For example, lieutenant general andorov in the ruins
creature ID 15471
At the beginning of the event, he'll run back to where he was

**Client version**: 
1.12.1
**Commit hash**: 
b8958bd9f66a38f00cbb8217d26a3767741ae324
**Operating system**: 
win10

**Comment by ratkosrb** [comment]
You'll have to be more specific than this. Show a video of what you are talking about.

**Comment by gamelgs** [comment]
https://youtu.be/ZxTrgq5k7bw

**Comment by gamelgs** [comment]
![1](https://user-images.githubusercontent.com/54333950/81002041-346e8000-8e7b-11ea-82f0-bf14482061eb.gif)
![2](https://user-images.githubusercontent.com/54333950/81002123-4fd98b00-8e7b-11ea-9173-c6f3fb0d4f6c.gif)
And these

**Comment by ratkosrb** [comment]
This bug should be fixed after the last commit. I tested with general andorov and he didn't run back anymore.

**Comment by gamelgs** [comment]
good job！！！general andorov is ok 

But other creatures still have problems.

**Comment by ratkosrb** [comment]
Give me creature ids.

**Comment by gamelgs** [comment]
ZG 
Razzashi Adder     ID 11372    GUID  49119
There's something wrong with its followers.
I think it's the same problem for all the creature followers.
Vanilla bropack V16 doesn't have this problem.

**Comment by ratkosrb** [comment]
Should be fixed https://github.com/vmangos/core/commit/1084b31421697675fa439e76ba9bc18cd1625949

**Comment by gamelgs** [comment]
Thank you very much.
